LIST_OF_EFFECTS = [
  "Preemption of local law",
  "Delegation of authority to agencies",
  "Reorganization of government entities",
  "Recognition of sovereignty (e.g. tribal or foreign)",
  "Specification of jurisdictional boundaries",
  "Override of common law",
  "Codification of case law",
  "Creation of a constitutional interpretation",
  "Suspension of laws (temporarily)",
  "Grant of emergency powers",
  "Imposition of sunset clauses",
  "Enabling referenda or public votes",
  "Declaration of legislative findings or policy",
  "Establishment of entitlements",
  "Criminalization of conduct",
  "Decriminalization of conduct",
  "Creation of private causes of action",
  "Elimination of private causes of action",
  "Specification of liability standards",
  "Specification of burden of proof",
  "Grant of immunity to private individuals or entities",
  "Grant of immunity to public officials",
  "Creation of affirmative defenses",
  "Establishment of contractual obligations",
  "Mandate for insurance coverage",
  "Requirement for disclosure or reporting",
  "Recognition of legal status (e.g. marriage)",
  "Creation of new courts or tribunals",
  "Establishment of procedural rules",
  "Establishment of evidentiary rules",
  "Creation of statute of limitations",
  "Creation of presumptions",
  "Removal of judicial discretion",
  "Mandate for judicial review",
  "Restriction on judicial review",
  "Creation of administrative remedies",
  "Requirement for exhaustion of remedies",
  "Specification of sentencing guidelines",
  "Creation of enforcement mechanisms",
  "Grant of injunction powers",
  "Authorization of class actions",
  "Establishment of arbitration or ADR",
  "Mandate for legal representation",
  "Specification of venue or jurisdiction rules",
  "Imposition of taxes",
  "Creation of tax exemptions",
  "Prohibition on certain business practices",
  "Imposition of licensing requirements",
  "Establishment of price controls",
  "Grant of subsidies or incentives",
  "Creation of monopolies or franchises",
  "Requirement for financial disclosures",
  "Setting of environmental standards",
  "Mandating labor conditions",
  "Enforcement of consumer protections",
  "Regulation of advertising",
  "Creation of safety standards",
  "Control over land use (zoning)",
  "Imposition of tariffs or quotas",
  "Restriction on foreign ownership",
  "Mandate for accessibility or accommodations",
  "Establishment of public programs",
  "Creation of registries or databases",
  "Mandate for public notice",
  "Authorization of funding",
  "Imposition of penalties or fines",
  "Authorization of searches or inspections",
  "Requirement for audits or oversight",
  "Authorization of intergovernmental agreements",
  "Requirement for public consultation",
  "Mandate for recordkeeping",
  "Creation of advisory bodies",
  "Mandate for training or education",
  "Establishment of eligibility criteria",
  "Recognition of holidays or memorials",
  "Symbolic recognition (e.g. apology or commemoration)",
  "Definition of terms or standards",
  "Trigger for automatic review or reauthorization",
  "Mandate for technological implementation",
  "Authorization for rulemaking",
  "Delegation of enforcement authority",
  "Damages enhancements (e.g. treble damages)",
  "Shifting of attorney's fees",
]